# Generated by Django 3.2.18 on 2023-04-29 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, to='Restaurant.Menu')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.customerorder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('customiztion', models.CharField(blank=True, max_length=200)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.menu')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.orderitem')),
            ],
        ),
    ]
