# Generated by Django 3.2.18 on 2023-04-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='finishTime',
        ),
    ]
