# Generated by Django 3.2.18 on 2023-05-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='menu_items',
        ),
        migrations.RenameField(
            model_name='orderitemdetails',
            old_name='customiztion',
            new_name='customization',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
