# Generated by Django 3.2.18 on 2023-04-28 01:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_remove_menu_finishtime'),
    ]

    operations = [
        migrations.AddField(
        model_name='customerorder',
        name='total_price',
        field=models.DecimalField(decimal_places=2, max_digits=6, default=0),
    ),

    ]
