# Generated by Django 3.2.18 on 2023-05-02 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_alter_customerorder_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 4, 2, 6, 715054, tzinfo=utc)),
        ),
    ]
