# Generated by Django 3.2.18 on 2023-05-02 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_alter_customerorder_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 2, 15, 54, 299230)),
        ),
    ]
